#The amount of power the compact solar module will produce
compactSolarProduction = 20
#The max amount of dynamites that can be held
maxDynamites = 50
#The amount of power the standard solar module will produce
standardSolarProduction = 20
#Disabled timed crafting
disableTimedCrafting = false
#The amount of power the basic solar module will produce
basicSolarProduction = 10
#Max drill size
drillSize = 4

